services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  django-web:
    build: .
    container_name: django-docker
    depends_on:
      - db
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod
volumes:
  postgres_data:
