# Generated by Django 5.2.2 on 2025-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_postcategory_alter_post_slug_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(db_comment='Defines if a post is published or hidden', default=False, help_text='Defines if a post is published or hidden'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(choices=[('JAPAN', 'Japan'), ('AUTOMOTIVE', 'Automotive')], db_comment='The category name', help_text='The category name', max_length=20, unique=True),
        ),
    ]
