# Generated by Django 5.2 on 2025-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_is_published_alter_postcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, db_comment='The URI encoded post title', help_text='The URI encoded post title', max_length=100, unique=True),
        ),
    ]
