# Generated by Django 5.2.2 on 2025-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(db_comment='The post thumbnail media URL', help_text='The post thumbnail media URL'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(choices=[('JAPAN', 'Japan'), ('FRANCE', 'France'), ('AUTOMOTIVE', 'Automotive')], db_comment='The category name', help_text='The category name', max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='PostThumbnail',
        ),
    ]
