name: Static analysis

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code & templates
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Ruff
        run: ruff check --output-format=github furai/ blog/

      - name: Run djLint
        run: djlint furai/templates blog/templates --profile=django --ignore=H031
