name: Static analysis

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github furai/
