name: Static analysis

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: Check typing with MyPy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install MyPy
        run: pip install mypy

      - name: Install Django stubs
        run: pip install 'django-stubs[compatible-mypy]'

      - name: Install dotenv
        run: pip install python-dotenv

      - name: Set DATABASE_URL from secret
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Install DB driver
        run: pip install psycopg2-binary

      - name: Run mypy
        run: |
          mypy --disallow-untyped-defs --namespace-packages --explicit-package-bases furai
