name: Static analysis

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: Check typing with MyPy
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: uv sync --locked

      - name: Set DATABASE_URL from secret
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Run mypy
        run: |
          uv run mypy --disallow-untyped-defs --namespace-packages --explicit-package-bases brdtheo blog
